name: trtc_demo
description: TRTC Demo.
publish_to: 'none'
version: 2.0.0
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  crypto: ^3.0.1
  flutter_styled_toast: ^2.1.3
  path_provider: ^2.0.15
  permission_handler: ^11.3.1

  flutter_easyloading: ^3.0.5
  tencent_rtc_sdk: 12.6.3
  super_player: 12.6.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # MP3 can choose not to pack, but web must be mp3 file
  assets:
    - images/avatar3_100.20191230.png
